In [1]:
from sqlalchemy import create_engine
import pandas as pd

# we connect with postgres to collect the historical data
engine = create_engine("postgresql://daniel:datascientest@localhost:5432/crypto_db")
                

query= "SELECT * FROM data_history;"
df = pd.read_sql(query, engine)
df.head(5)

,id,market,timestamp_open,open,high,low,price,volume,timestamp_close
0,1,BTCUSDT,1764723120000,91747.99,91747.99,91689.71,91689.73,9.87419,1764723179999
1,2,BTCUSDT,1764723180000,91689.73,91693.07,91628.93,91639.92,7.23424,1764723239999
2,3,BTCUSDT,1764723240000,91639.92,91639.93,91550.54,91550.55,5.89557,1764723299999
3,4,BTCUSDT,1764723300000,91550.54,91554.20,91511.50,91511.50,5.59798,1764723359999
4,5,BTCUSDT,1764723360000,91511.51,91511.51,91415.03,91424.13,14.87505,1764723419999

### Clean Data ###

In [5]:
df['market'] = df['market'].astype(str).str.lower()
df.head(5)

,id,market,timestamp_open,open,high,low,price,volume,timestamp_close
0,1,btcusdt,1764723120000,91747.99,91747.99,91689.71,91689.73,9.87419,1764723179999
1,2,btcusdt,1764723180000,91689.73,91693.07,91628.93,91639.92,7.23424,1764723239999
2,3,btcusdt,1764723240000,91639.92,91639.93,91550.54,91550.55,5.89557,1764723299999
3,4,btcusdt,1764723300000,91550.54,91554.20,91511.50,91511.50,5.59798,1764723359999
4,5,btcusdt,1764723360000,91511.51,91511.51,91415.03,91424.13,14.87505,1764723419999

Let check the colonnes type and passt it if necessary

In [6]:
df.info()
# we there all well until the timestamp which have to be convert in datetime

<class 'pandas.DataFrame'>
RangeIndex: 518400 entries, 0 to 518399
Data columns (total 9 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   id               518400 non-null  int64
 1   market           518400 non-null  str
 2   timestamp_open   518400 non-null  int64
 3   open             518400 non-null  float64
 4   high             518400 non-null  float64
 5   low              518400 non-null  float64
 6   price            518400 non-null  float64
 7   volume           518400 non-null  float64
 8   timestamp_close  518400 non-null  int64
dtypes: float64(5), int64(3), str(1)
memory usage: 35.6 MB

In [7]:
df['timestamp_open'] = pd.to_datetime(df['timestamp_open'], unit='ms')
df['timestamp_close'] = pd.to_datetime(df['timestamp_close'],unit='ms')
df.head(5)

,id,market,timestamp_open,open,high,low,price,volume,timestamp_close
0,1,btcusdt,2025-12-03 00:52:00,91747.99,91747.99,91689.71,91689.73,9.87419,2025-12-03 00:52:59.999
1,2,btcusdt,2025-12-03 00:53:00,91689.73,91693.07,91628.93,91639.92,7.23424,2025-12-03 00:53:59.999
2,3,btcusdt,2025-12-03 00:54:00,91639.92,91639.93,91550.54,91550.55,5.89557,2025-12-03 00:54:59.999
3,4,btcusdt,2025-12-03 00:55:00,91550.54,91554.20,91511.50,91511.50,5.59798,2025-12-03 00:55:59.999
4,5,btcusdt,2025-12-03 00:56:00,91511.51,91511.51,91415.03,91424.13,14.87505,2025-12-03 00:56:59.999

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 518400 entries, 0 to 518399
Data columns (total 9 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   id               518400 non-null  int64
 1   market           518400 non-null  str
 2   timestamp_open   518400 non-null  datetime64[ms]
 3   open             518400 non-null  float64
 4   high             518400 non-null  float64
 5   low              518400 non-null  float64
 6   price            518400 non-null  float64
 7   volume           518400 non-null  float64
 8   timestamp_close  518400 non-null  datetime64[ms]
dtypes: datetime64[ms](2), float64(5), int64(1), str(1)
memory usage: 35.6 MB

Let now check the NAN values for each columns

In [9]:
df.isna().sum()
# great we have no missing values

id                 0
market             0
timestamp_open     0
open               0
high               0
low                0
price              0
volume             0
timestamp_close    0
dtype: int64

Let now make sure that the chronological history is respected

In [10]:
# we sort the DataFrame by the timestamp_open
df = df.sort_values(by='timestamp_open', ascending=True)

# and reinitialize the index
df = df.reset_index(drop=True)
df.head(5)

,id,market,timestamp_open,open,high,low,price,volume,timestamp_close
0,1,btcusdt,2025-12-03 00:52:00,91747.99,91747.99,91689.71,91689.73,9.87419,2025-12-03 00:52:59.999
1,2,btcusdt,2025-12-03 00:53:00,91689.73,91693.07,91628.93,91639.92,7.23424,2025-12-03 00:53:59.999
2,3,btcusdt,2025-12-03 00:54:00,91639.92,91639.93,91550.54,91550.55,5.89557,2025-12-03 00:54:59.999
3,4,btcusdt,2025-12-03 00:55:00,91550.54,91554.20,91511.50,91511.50,5.59798,2025-12-03 00:55:59.999
4,5,btcusdt,2025-12-03 00:56:00,91511.51,91511.51,91415.03,91424.13,14.87505,2025-12-03 00:56:59.999

Let have a look if there Duplicates anywhere

In [11]:
df.duplicated().sum()
# we also have no duplicate, so we can continue with the feature Engineering

np.int64(0)

In [12]:
df.duplicated(subset=['timestamp_open', 'market']).sum()

np.int64(257988)

In [13]:
df = df.sort_values(by=['market', 'timestamp_open']).reset_index(drop=True)
df = df.drop_duplicates(subset=['timestamp_open', 'market'], keep='first')
df = df.reset_index(drop=True)

# let check
print("the rest of duplicate :", df.duplicated(subset=['timestamp_open', 'market']).sum())

the rest of duplicate : 0

Before starting with feature Engineering and create new Columns as Indicators for a better Prediction. we have first to look after the Target feature which we don't have until now. The Goal of our ML model will be to predict if we can sell or not. So a classification Problem. Let now beginn with.

### Creation of the Target Feature ####

In [14]:

LOOKAHEAD = 3 # we look at 3 klines in the future
df['future_close'] = df['price'].shift(-LOOKAHEAD)
df['target'] = (df['future_close'] > df['price']).astype(int)
df = df.drop(columns=['future_close'])

# On supprime les 'LOOKAHEAD' dernières lignes du dataset car elles n'ont pas de futur
df = df.dropna(subset=['target']).reset_index(drop=True)
df.head(3)
# target : 1 -> buy / 0 -> sell

,id,market,timestamp_open,open,high,low,price,volume,timestamp_close,target
0,1,btcusdt,2025-12-03 00:52:00,91747.99,91747.99,91689.71,91689.73,9.87419,2025-12-03 00:52:59.999,0
1,2,btcusdt,2025-12-03 00:53:00,91689.73,91693.07,91628.93,91639.92,7.23424,2025-12-03 00:53:59.999,0
2,3,btcusdt,2025-12-03 00:54:00,91639.92,91639.93,91550.54,91550.55,5.89557,2025-12-03 00:54:59.999,0

We Seplit now

In [15]:
# 2. SPLIT TRAIN / TEST
split_index = int(len(df) * 0.80)
df_train = df.iloc[:split_index].copy().reset_index(drop=True)
df_test = df.iloc[split_index:].copy().reset_index(drop=True)

### Feature Engineering ###

In [24]:
import pandas_ta as ta

def add_indicators(data):
    # Create a copy to prevent SettingWithCopyWarning from Pandas
    df_feat = data.copy()
    
    # --- 1. TRENDS ---
    # Exponential Moving Averages (20/50 crossover strategy)
    df_feat['ema_20'] = ta.ema(df_feat['price'], length=20)
    df_feat['ema_50'] = ta.ema(df_feat['price'], length=50)
    # Moving Average Convergence Divergence (Trend + Momentum)
    macd = ta.macd(df_feat['price'], fast=12, slow=26, signal=9)
    df_feat = pd.concat([df_feat, macd], axis=1)
    
    # --- 2. VOLATILITY ---
    # Bollinger Bands (BB)
    bbands = ta.bbands(df_feat['price'], length=20, std=2)
    df_feat = pd.concat([df_feat, bbands], axis=1)
    # Average True Range (ATR) - Excellent for determining stop-loss size
    df_feat['atr'] = ta.atr(df_feat['high'], df_feat['low'], df_feat['price'], length=14)
    
    # --- 3. MOMENTUM ---
    # Relative Strength Index (RSI)
    df_feat['rsi'] = ta.rsi(df_feat['price'], length=14)
    
    # --- 4. SHORT-TERM MARKET DYNAMICS ---
    # Period-to-period price return
    df_feat['returns'] = df_feat['price'].pct_change()
    # Short-term volume momentum (current volume compared to its 5-period rolling mean)
    df_feat['vol_momentum'] = df_feat['volume'] / df_feat['volume'].rolling(window=5).mean()
    
    # --- CLEANING ---
    # Lagged indicators (like EMA 50) generate NaN values in the initial rows.
    # We drop them to prevent Machine Learning models from crashing.
    df_feat = df_feat.dropna().reset_index(drop=True)
    
    return df_feat

In [25]:
df_train_features = add_indicators(df_train)
df_test_features = add_indicators(df_test)
df_train_features.head(3)

,id,market,timestamp_open,open,high,low,price,volume,timestamp_close,target,...,MACDs_12_26_9,BBL_20_2.0_2.0,BBM_20_2.0_2.0,BBU_20_2.0_2.0,BBB_20_2.0_2.0,BBP_20_2.0_2.0,atr,rsi,returns,vol_momentum
0,50,btcusdt,2025-12-03 01:41:00,91905.62,91940.48,91887.55,91934.66,5.12797,2025-12-03 01:41:59.999,1,...,54.161105,91818.625186,91903.2640,91987.902814,0.184191,0.685470,69.407643,55.379808,0.000316,0.755131
1,51,btcusdt,2025-12-03 01:42:00,91934.66,91946.78,91918.94,91942.90,3.31298,2025-12-03 01:42:59.999,1,...,51.858016,91818.963336,91905.4090,91991.854664,0.188119,0.716847,66.438525,56.055610,0.000090,0.473747
2,52,btcusdt,2025-12-03 01:43:00,91942.89,91942.90,91936.31,91939.90,4.81200,2025-12-03 01:43:59.999,1,...,49.928448,91820.410966,91907.8795,91995.348034,0.190340,0.683040,62.163631,55.724696,-0.000033,1.150561

Let now transform the data so that the Model will not consider a Attribut more important than another

In [26]:
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, accuracy_score

Let separate X and Y for training

In [27]:
columns_to_drop = ['timestamp_open', 'timestamp_close', 'market', 'target']

X_train = df_train_features.drop(columns=columns_to_drop)
y_train = df_train_features['target']

X_test = df_test_features.drop(columns=columns_to_drop)
y_test = df_test_features['target']

Scaling of data

In [28]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

### Model Fitting and Probability

In [29]:
# Initialize and train the model
model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train_scaled, y_train)

# Get standard binary predictions (0 or 1)
y_pred = model.predict(X_test_scaled)

# Get precise probabilities of buying (class 1)
buy_probabilities = model.predict_proba(X_test_scaled)[:, 1]

### Model Evaluation

In [33]:
# Check the evaluation
print("Accuracy Score:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

Accuracy Score: 0.5070722988815005

Classification Report:
               precision    recall  f1-score   support

           0       0.51      0.59      0.55     26261
           1       0.50      0.43      0.46     25773

    accuracy                           0.51     52034
   macro avg       0.51      0.51      0.50     52034
weighted avg       0.51      0.51      0.50     52034

### Results

In [34]:
# We build a clean DataFrame to visualize the results
results_df = pd.DataFrame({
    'Actual_Target': y_test,
    'Model_Prediction': y_pred,
    'Buy_Probability': buy_probabilities
})

# we define our confidence threshold
CONFIDENCE_THRESHOLD = 0.65

# Create a custom signal: 1 if probability > threshold, else 0
results_df['Filtered_Signal'] = (results_df['Buy_Probability'] > CONFIDENCE_THRESHOLD).astype(int)

# Let's see how many trades we actually take with this filter
print(f"Total signals without filter: {results_df['Model_Prediction'].sum()}")
print(f"Total signals with 65% filter: {results_df['Filtered_Signal'].sum()}")

Total signals without filter: 21794
Total signals with 65% filter: 1382

### Save the Model and the scaler for our Bot

In [35]:
import joblib

# we save the Model
joblib.dump(model, 'crypto_model.joblib')

# and save the scaler
joblib.dump(scaler, 'crypto_scaler.joblib')

print("successful save of model and scaler !")

successful save of model and scaler !